### ISSUE TITLE
关于贵站小程序“过度参考”本人原创小程序的一些询问

### ISSUE THREAD

**Issue by Jeff2Ma** [iamxjb/winxin-app-watch-life.net#1]
你好，发现贵站的小程序当前（7.20）上看的版本在如下地方有“参考”本人的微信小程序 “devework+” 的情况：
1. “专题”tab 页面， tab 的标题，单卡片 图+标题+说明 的交互方式。
2. “我”tab 页面，tab 的标题跟 icon，整体布局及功能本身几乎一致，诸如“阅读记录仅保留 xxx”的文案，阅读记录也是20条也是惊人的一致。

本人小程序 “devework+”二维码：

![https://res.jianhui.org/wxapp/images/qr-r@2x.jpg](https://res.jianhui.org/wxapp/images/qr-r@2x.jpg)

代码上因为我的是闭源的，且功能本身实现起来不难，所以本 issue 无意指代码层面的问题。但以上**从时间点上我可以举证为本人原创**（包括代码及其相关素材）。因此希望楼主能予以说明。

楼主主动开源你的小程序是好事，但也希望能尊重原创。是的，思路、UI、交互这些无形的东西也是原创的范畴。本人的小程序的两个 tab 内的页面被楼主以这样的形式搬过去，且挂上了开源的名号被广知，本人自然是想发出一些声音。

最后说明：发起本 issue 无它，以上的点其实楼主都可以用（毕竟这些又没法申请专利且也无法让楼主不准用），但希望至少在 README 说明下，提及下。

**Comment by iamxjb** [comment]
好的，我会在readme上加相关声明。

**Comment by Jeff2Ma** [comment]
thanks :)

**Comment by iamxjb** [comment]
不要意思，交了朋友，我的微信号：iamxjb，其实我很欣赏你的设计。:-)
