### ISSUE TITLE
关于下拉翻页无法加载评论的一个小bug

### ISSUE THREAD

**Issue by hezhengxu2018** [iamxjb/winxin-app-watch-life.net#24]
在使用这个小程序的过程中出现了一个比较奇怪的bug，连接默认的wp的时候非常正常，评论是可以正常加载的，但是连接自己的wp的时候就没办法加载评论，提交过评论才可以显示，而且每次都需要评论一下才能正常加载评论的bug。
一开始一直以为是自己wp的设置问题，一直百思不得解，最后发现在连接默认的wp的时候文章拉到低有一个加载的动画，遂开始怀疑是不是自己文章太短了没能让小程序尝试加载，试了一下果然是这样：
**当文章足够长到出现滚动条的时候能让滚动条拉到低才会自动加载评论，如果文章过短一页就能显示完的时候就不会加载评论**
有时间的话看自己能不能改一下代码，提交一个pull request，能力有限的话就等作者更新

**Comment by webzol** [comment]
好的

**Comment by iamxjb** [comment]
确实有这个问题，上拉加载需要超过一屏的高度才会触发。
