### ISSUE TITLE
https://www.****.com/wp-json/watch-life-net/v1/post/swipe 报500错误是什么原因呢？报错如下

### ISSUE THREAD

**Issue by ljl3937** [iamxjb/winxin-app-watch-life.net#25]
{"code":"success","message":" get post swipe error","status":"500"}

**Comment by webzol** [comment]
没有请求到




| |
未*
邮箱：web_geek@163.com
|

签名由 网易邮箱大师 定制

在2018年11月01日 23:15，加加笔记 写道：

{"code":"success","message":" get post swipe error","status":"500"}

**Comment by webzol** [comment]
我明天了电脑看




| |
未*
邮箱：web_geek@163.com
|

签名由 网易邮箱大师 定制

在2018年11月01日 23:33，Kit. 写道：
没有请求到




| |
未*
邮箱：web_geek@163.com
|

签名由 网易邮箱大师 定制

在2018年11月01日 23:15，加加笔记 写道：

{"code":"success","message":" get post swipe error","status":"500"}
