### ISSUE TITLE
网站没开启https怎么办

### ISSUE THREAD

**Issue by skating507** [iamxjb/winxin-app-watch-life.net#3]
如题，发现网站没有开启https，小程序没办法使用。

**Comment by poisonboy** [comment]
小程序目前只支持https，而且现在很多浏览器都不再信任http，建议你开启ssl。
如果只是测试，可以在小程序开发工具-设置-项目设置里选择 -不校验安全域名、TLS 版本以及 HTTPS 证书

**Comment by iamxjb** [comment]
poisonboy 回答也是我可以给的答案

**Comment by poisonboy** [comment]
建议你看下wp_rest和小程序官方文档，如果实在解决不了，请联系群主付费帮你

**Comment by abigbone** [comment]
最简单的是你选择个腾讯或者阿里云服务器，有免费申请域名证书的 ，或者你也可以用lnmp 套件集成了申请工具， 调试好服务器环境的https 。

**Comment by PascalSun** [comment]
Letencrypt
