### ISSUE TITLE
是否支持woocommerce？

### ISSUE THREAD

**Issue by akeliduo** [iamxjb/winxin-app-watch-life.net#35]
网站如果是商城，可以使用吗？

**Comment by iamxjb** [comment]
> 网站如果是商城，可以使用吗？

不支持

**Comment by iamxjb** [comment]
> 网站如果是商城，可以使用吗？

你可以去看看这个小程序：https://www.qwqoffice.com/woocommerce-to-wechatapp/

**Comment by xepin** [comment]
希望能支持更多post类型

**Comment by iamxjb** [comment]
> 希望能支持更多post类型

目前只支持文章和页面类型
