### ISSUE TITLE
本年度最受欢迎这里可以改为分类吗

### ISSUE THREAD

**Issue by skating507** [iamxjb/winxin-app-watch-life.net#4]
本年度最受欢迎和总排行 可以改为其中一个分类吗？现在这个感觉不是很好

**Comment by poisonboy** [comment]
可以，如果你会简单代码的话，可以做成任何你想做的样子。你可以看看我头像的小程序，就是基于群主的开源程序做的。

**Comment by skating507** [comment]
就是测试了没有成功

**Comment by skating507** [comment]
//获取热点文章
  getTopHotPosts(flag){      
      var url = HOST_URI;
      if(flag ==1)
      {
        url +="posts?per_page=5&&page=1&categories=2836"
      }
      else if(flag==2)
      {
        url += "posts?per_page=5&&page=1&categories=18212"
      }

      return url;
  },
我直接改成这样好像不行，哪里出问题了呢

**Comment by iamxjb** [comment]
热点文章是基于我自己定义的api来显示的，并非用的官方的api，所以你的方法是没法生效的，如果你想改为分类的，需要修改我写得wordpress 插件。

**Comment by skating507** [comment]
我修改插件老是显示出错。
