### ISSUE TITLE
文章无图片时搜索列表页、类目页的文章列表图片均不能显示

### ISSUE THREAD

**Issue by jiazhaoyang** [iamxjb/winxin-app-watch-life.net#46]
如果首页的文章无图片时，会用默认的图片代替，但其他的列表比如搜索结果页、类目页的列表图片就为空了。
![WechatIMG20](https://user-images.githubusercontent.com/12572683/88932904-48c2ed00-d2b1-11ea-8461-56c37ea8a65e.jpeg)

![WechatIMG19](https://user-images.githubusercontent.com/12572683/88932866-3943a400-d2b1-11ea-8543-cd6e70e31984.jpeg)

**Comment by iamxjb** [comment]
已修复
