### ISSUE TITLE
获取用户点赞的头像不能正确获取

### ISSUE THREAD

**Issue by fantingsheng** [iamxjb/winxin-app-watch-life.net#5]
获取到的都是默认头像

**Comment by iamxjb** [comment]
这个问题有可能是微信用户没有设置头像。你需要说明下具体的问题。

**Comment by fantingsheng** [comment]
你的点赞用户的头像字段是用户的openid不是头像链接

**Comment by iamxjb** [comment]
点赞的记录在数据库记录的是openid，但用户的头像数据放在用户表里，会通过一个关联来显示点赞用户的头像，你可以直接看看json数据就明白了。
