### ISSUE TITLE
请问ui.scss无法导入如何解决？

### ISSUE THREAD

**Issue by yaunsine** [iamxjb/winxin-app-watch-life.net#59]
![image](https://user-images.githubusercontent.com/54234422/159015371-0aec4223-b82b-46e2-9728-81d3bc9baf01.png)

在console中出现了以下错误，导致页面无法显示：
`[ WXSS 文件编译错误] ./app.wxss
File not found: mp-cu/colorUI/scss/ui.scss(env: Windows,mp,1.05.2203181; lib: 2.23.0)`

本人对前端知识不熟悉，还请大佬解答！！！

**Comment by yaunsine** [comment]
已解决

**Comment by iamxjb** [comment]
需要整体导入小程序，不是新建。

**Comment by lanhao1105** [comment]
我也遇到了，怎么解决啊
