### ISSUE TITLE
与jwt-auth插件冲突，导致小程序无法获取文章信息

### ISSUE THREAD

**Issue by kemistep** [iamxjb/winxin-app-watch-life.net#60]
![image](https://user-images.githubusercontent.com/16223610/193497694-d2a8e20b-10f5-44f1-b724-0b5ed4dd5afe.png)

把jwt-auth禁用就可以获取文章，开启就不能；

但是需要使用 jwt-auth 这个插件；

有解决办法没？

**Comment by iamxjb** [comment]
可能 jwt-auth 插件禁用了 rest api  导致api无法正常访问
